### ISSUE TITLE
Transfer any issues needed from report

### ISSUE THREAD

**Issue by CameronBrooks11** [werocketry/RocketFlightSim#2]
Below is from our final report, please open any issues mentioned here that have yet to be addressed:

### Flight Simulator Improvements

The effects of wind are yet to be addressed in the custom flight
simulator. Addressing how wind affects a rocket's flightpath was
deliberately left until the late stages of the project for two reasons.
Firstly, because it doesn't have as significant an effect on the rocket
as the principal forces already considered[^2]. Secondly, because it has
taken a significant amount of time to contrive an accurate way to
account for wind in the simulation of a point mass rocket. Factoring the
effects of wind into the custom flight simulator is underway and is
expected to be completed by the end of April.

Another key improvement to the flight simulator before competition will
be feeding it an updated drag curve from the final version of the CFD,
which will be discussed more later in this section.

The simulator will be further optimized in the case that model
predictive control is the control scheme that the airbrakes system uses,
and a custom version of the simulator to be used for that purpose is
already in development. Model predictive control will be discussed in
detail later in this section.

**Comment by chasgior214** [comment]
Thanks for checking those are all being tracked. I've got them all either in TODOs somewhere in the code (which I'll turn into issues/add to the project soon) or in my list of things to do that I'm also going to turn into issues/add to the project.

**Comment by chasgior214** [comment]
I'm also tracking that I'll be bringing over some of the issues from the capstone repo that didn't come over here with the fork/split/owner transfer
